color:
  saturation: 0.98527
  brandStrength: 0.1446075
  rhythmicContrast: 0.09682391
  brandColors:
    - '#060606'
    - '#F2F2F2'
    - '#5C5C5C'
    - '#9A9A9A'
  lightness: 0.3824626
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 1
typography_spectrum: 0.4390681
name: Kyle Dillingham
