layout_spectrum: 1
color:
  saturation: 0.98527
  lightness: 0.3824626
  brandStrength: 0.1446075
  brandColors:
    - '#060606'
    - '#F2F2F2'
    - '#5C5C5C'
    - '#9A9A9A'
  rhythmicContrast: 0.09682391
typography_spectrum: 0.4390681
name: Kyle Dillingham
